# -*- coding: utf-8 -*-
"""model-training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Emg-ivzeSLYg4avfgPPkviEWam9xKzjq
"""

# Commented out IPython magic to ensure Python compatibility.
# Importing the required libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
print("Imported all required libraries")

# Importing the dataset
mobile_classification_dataset = pd.read_csv('/content/drive/MyDrive/ML/train.csv')
mobile_classification_dataset.head()

# Validating the columns
mobile_classification_dataset.info()

# Performing exploratory data analysis to understand if there are related features.
plt.figure(figsize=(20,10))
X = mobile_classification_dataset.drop('price_range', axis=1)
correlation_matrix = X.corr()
sns.heatmap(
    correlation_matrix,
    annot=True,          # Show the correlation values
    cmap='coolwarm',     # Color gradient (blue for negative, red for positive)
    fmt=".2f",           # Format to 2 decimal places
    linewidths=0.5,      # Add gridlines
    vmin=-1, vmax=1      # Set the scale from -1 to 1
)
plt.show()

# Looking over the data it looks very balanced and none of features are correlated hence we should be good to keep all features.

# We need to scale the data. We can go with min max scaling
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
mobile_classification_dataset_scaled = scaler.fit_transform(mobile_classification_dataset.drop('price_range', axis=1))
mobile_classification_dataset_scaled = pd.DataFrame(mobile_classification_dataset_scaled, columns=mobile_classification_dataset.columns[:-1])
mobile_classification_dataset_scaled.head()

from sklearn.model_selection import train_test_split
target = mobile_classification_dataset['price_range']

X_train, X_test, y_train, y_test = train_test_split(mobile_classification_dataset_scaled, target, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

print("Initializing the model")
models = {
    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'K-Nearest Neighbors': KNeighborsClassifier(),
    'Naive Bayes': GaussianNB()
}

# Training and evaluating the model.
from sklearn.metrics import accuracy_score, roc_auc_score, precision_score, recall_score, f1_score, matthews_corrcoef

results = []
for name, model in models.items():
    print(f"Training {name} model...")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    auc_core = roc_auc_score(y_test, y_prob, multi_class='ovr')
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')
    f1 = f1_score(y_test, y_pred, average='macro')
    mcc = matthews_corrcoef(y_test, y_pred)

    results.append([name, accuracy, auc_core, precision, recall, f1, mcc])

results_df = pd.DataFrame(results, columns=['Model', 'Accuracy', 'AUC-Core', 'Precision', 'Recall', 'F1 Score', 'MCC'])
print(results_df.to_markdown(index=False))

import joblib
import os

os.makedirs('model', exist_ok=True)
joblib.dump(scaler, 'model/scaler.joblib')
joblib.dump(models['Logistic Regression'], 'model/logistic_regression_model.joblib')
joblib.dump(models['Decision Tree'], 'model/decision_tree_model.joblib')
joblib.dump(models['Naive Bayes'], 'model/naive_bayes_model.joblib')
joblib.dump(models['K-Nearest Neighbors'], 'model/knn_model.joblib')
joblib.dump(models['Random Forest'], 'model/random_forest_model.joblib')