# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17BDcMCOzDoDkgO0kji0Hv7rakRxHzo4m
"""

import streamlit as st
import pandas as pd
import joblib
import os
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score,
    recall_score, f1_score, matthews_corrcoef, confusion_matrix
)

st.set_page_config(page_title="Mobile Price Classification based on its features", layout="wide")
st.title("📱 Mobile Price Classification Models")
st.markdown("This page is to validate and compare multiple classification models on test data set to classify mobile price.")
st.sidebar.header("Upload data (Only csv file upload is supported)")

file_uploaded = st.sidebar.file_uploader("Upload your data here", type=["csv"])

st.sidebar.header("Model Selection")
user_choice = st.sidebar.selectbox("Select a machine learning model",
                                    ["All", "Logistic Regression", "Decision Tree", "Random Forest", "K-Nearest Neighbors", "Naive Bayes"])

file_mapping = {
    "Logistic Regression": "logistic_regression_model.joblib",
    "Decision Tree": "decision_tree_model.joblib",
    "Random Forest": "random_forest_model.joblib",
    "K-Nearest Neighbors": "knn_model.joblib",
    "Naive Bayes": "naive_bayes_model.joblib"
}

if file_uploaded is not None:
    try:

      test_csv = pd.read_csv(file_uploaded)
      st.subheader("Preview of the uploaded data")
      st.write(test_csv.head())
      X_test = test_csv.drop("price_range", axis=1)
      y_test = test_csv["price_range"]

      X_test_scaled = joblib.load(os.path.join("model", "scaler.joblib")).transform(X_test)

      if user_choice == "All":
        st.subheader("Comparing metrics of all models")
        results = []
        for model_name, model_file in file_mapping.items():
          model = joblib.load(os.path.join("model", model_file))
          y_pred = model.predict(X_test_scaled)
          y_pred_proba = model.predict_proba(X_test_scaled)
          accuracy = accuracy_score(y_test, y_pred)
          auc_core = roc_auc_score(y_test, y_pred_proba, multi_class='ovr')
          precision = precision_score(y_test, y_pred, average='macro')
          recall = recall_score(y_test, y_pred, average='macro')
          f1 = f1_score(y_test, y_pred, average='macro')
          mcc = matthews_corrcoef(y_test, y_pred)
          results.append([model_name, accuracy, auc_core, precision, recall, f1, mcc])

        if results:
          results_df = pd.DataFrame(results, columns=['Model', 'Accuracy', 'AUC-Core', 'Precision', 'Recall', 'F1 Score', 'MCC'])
          st.dataframe(results_df.style.format({
              "Accuracy": "{:.4f}", "AUC": "{:.4f}",
              "Precision": "{:.4f}", "Recall": "{:.4f}",
              "F1 Score": "{:.4f}", "MCC": "{:.4f}"
          }), width='stretch')
          st.write("Comparing accuracy for all the models")
          fig, ax = plt.subplots(figsize=(8, 4))
          sns.barplot(x="Accuracy", y="Model", data=results_df, ax=ax, palette="viridis")
          ax.set_xlim(0, 1.0) # Accuracy is between 0 and 1
          for p in ax.patches:
            ax.annotate(f"{p.get_width():.4f}", (p.get_width() + 0.01, p.get_y() + 0.5))
          st.pyplot(fig)
      else:
        model = joblib.load(os.path.join("model", file_mapping[user_choice]))
        y_pred = model.predict(X_test_scaled)
        y_pred_proba = model.predict_proba(X_test_scaled)
        st.subheader(f"Metrics for {user_choice} model")
        col1, col2, col3 = st.columns(3)
        col1.metric("Accuracy", f"{accuracy_score(y_test, y_pred):.4f}")
        col2.metric("AUC Score", f"{roc_auc_score(y_test, y_pred_proba, multi_class='ovr'):.4f}")
        col3.metric("MCC Score", f"{matthews_corrcoef(y_test, y_pred):.4f}")
        col4, col5, col6 = st.columns(3)
        col4.metric("Precision", f"{precision_score(y_test, y_pred, average='macro'):.4f}")
        col5.metric("Recall", f"{recall_score(y_test, y_pred, average='macro'):.4f}")
        col6.metric("F1 Score", f"{f1_score(y_test, y_pred, average='macro'):.4f}")
        st.divider()
        st.subheader("Confusion Matrix")
        cm = confusion_matrix(y_test, y_pred)
        fig, ax = plt.subplots(figsize=(5, 4))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax)
        ax.set_xlabel('Predicted')
        ax.set_ylabel('True')
        st.pyplot(fig)
    except Exception as e:
      st.error(f"Error occurred while processing the file and running model on it {e}")